name: ciocio_team_generator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.1
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.4+3
  keyboard_visibility: ^0.5.6
  google_fonts: ^0.3.9
  flutter_device_type: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4


#  run these for app icon update
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - google_fonts/

